name: my_flutter_app
description: "A Trading Card Game Collection Manager"
publish_to: 'none'
version: 1.0.0+1  # Increment this for app store updates

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.0  # For date formatting
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1  # Add this for better image caching
  fl_chart: ^0.66.0
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  
  # Networking & Data
  http: ^1.2.0  # Make sure this is included
  crypto: ^3.0.3

  # URL Launcher
  url_launcher: ^6.2.5

  # Google Sign-In
  google_sign_in: ^6.1.5  # Add this line

  # Image Picker
  image_picker: ^1.0.7  # Add this line

  # Lottie
  lottie: ^2.7.0  # Add this line with the correct version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/names.json
    - assets/avatars/
    - assets/images/  # Add this line
    - assets/images/google_logo.png  # Add this line specifically
    - assets/backgrounds/
    - assets/animations/  # Add this line

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700