name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.15.3  # Use the latest version
  cloud_firestore: ^4.15.5
  
  # API and Networking
  http: ^1.1.0
  cached_network_image: ^3.2.3
  fl_chart: ^0.66.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/names.json