// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError('Unsupported platform');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDwlupCmbD0GnWChbm6CajPD9kzMD1vM',
    appId: '1:977857362801:web:3137453dd075d3cb3954d0',
    messagingSenderId: '977857362801',
    projectId: 'card-app-95bcb',
    authDomain: 'card-app-95bcb.firebaseapp.com',
    storageBucket: 'card-app-95bcb.firebasestorage.app',
  );
}